vich_uploader:
    db_driver: orm
    mappings:
        recette_image:
            uri_prefix: /images/recettes
            upload_destination: '%kernel.project_dir%/public/images/recettes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
